# This file was generated by GoReleaser. DO NOT EDIT.
cask "lokx-fleet-agent" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "d4b1da8ca2f8993eb25f534a750a896e33859f157dba870c77f914a5fd2809fe"
      url "https://www.lokx.ai/fleet/lokx-fleet-agent--v#{version}--darwin-arm64.tar.gz"
    end
  end

  name "lokx-fleet-agent"
  desc ""
  homepage "https://www.lokx.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lokx-fleet-agent"

  postflight do
    system_command "/bin/mkdir", args: ["-p", "/etc/lokx-fleet"], sudo: true

    unless File.exist?("/etc/lokx-fleet/agent.env")
      system_command "/bin/cp", args: ["#{staged_path}/agent.env", "/etc/lokx-fleet/agent.env"], sudo: true
    end
  end

  uninstall_postflight do
    if File.exist?("/etc/lokx-fleet/agent.env")
      system_command "/bin/rm", args: ["-f", "/etc/lokx-fleet/agent.env"], sudo: true
    end
  end

  # No zap stanza required

end
