# This file was generated by GoReleaser. DO NOT EDIT.
cask "lokx-fleet-agent" do
  version "0.3.2"

  on_macos do
    on_arm do
      sha256 "6d21c2a0d6bcebaf6bbb49001b83e4ac0f6c4f177bb13cef0d8c746af2f3b858"
      url "https://www.lokx.ai/fleet/lokx-fleet-agent--v#{version}--darwin-arm64.tar.gz"
    end
  end

  name "lokx-fleet-agent"
  desc ""
  homepage "https://www.lokx.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lokx-fleet-agent"

  postflight do
    system_command "/bin/mkdir", args: ["-p", "/etc/lokx-fleet"], sudo: true

    unless File.exist?("/etc/lokx-fleet/agent.env")
      system_command "/bin/cp", args: ["#{staged_path}/agent.env", "/etc/lokx-fleet/agent.env"], sudo: true
    end
  end

  uninstall_postflight do
    if File.exist?("/etc/lokx-fleet/agent.env")
      system_command "/bin/rm", args: ["-f", "/etc/lokx-fleet/agent.env"], sudo: true
    end
  end

  # No zap stanza required

end
